# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029ab08074fbe7184a0bb928512796f6752e11cba79808a3b2d738f66ee2718760538569d4015ae461ef98b753134074fcaee7fcaa0cd89d2754217f35d6b0c9

test:
  secret_key_base: 418ac39c9c36d2995fa790a1ab1be1dedb5aadb866e4e58b912abcafdea98fc4ec8bd18544c9b90362309b6b5028a11fccbadd53e4821fa0bfc395fc25394dcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
